anarazel/pg-vm-images

files/bsd/rc.local.sh
packer/bsd/netbsd_postgres.pkr.hcl
packer/bsd/netbsd_vanilla.pkr.hcl
packer/bsd/openbsd_postgres.pkr.hcl
packer/bsd/openbsd_vanilla.pkr.hcl
scripts/bsd/clear_users_and_ssh_keys.sh

I realized that since we are creating postgres images from vanilla images, vanilla images' rc.local script will create users and these users will exist in postgres images. We need to remove these users. This PR aims to fix that problem.

Clear users and ssh keys before publishing image

---

packer/netbsd_openbsd.pkr.hcl

I was working on some openbsd improvements and realized that we were using incorrect images(old images) while using compute_engine_instances.
We were publishing openbsd-netbsd images without 'version' tag, but we were [calling them with 'version' tag](https://github.com/anarazel/postgres/blob/meson/.cirrus.yml#L166). So, actually we were not using recently published images but the old ones.

fix: correct openbsd-netbsd image families

---

.cirrus.yml
packer/windows.pkr.hcl
packer/windows_container.pkrvars.hcl
scripts/windows_install_mingw64.ps1

Adding `$ErrorActionPreference = 'Stop'` is solving VM issue but when it is added to container, it doesn't run scripts. So, I used `Invoke-Expression` for containers. I tried using wrong commands, exit with other than 0, throwing errors and all of them stopped the execution.
For the containers:
We need to use `$ErrorActionPreference = 'Stop'` in inline scripts too because packer is putting these inline commands to the *.ps1; then it executes these files.
But here could be some problems(?):
* Only `Invoke-Expression` worked correctly but there are some issues about that: 
> [Take reasonable precautions when using the Invoke-Expression cmdlet in scripts. When using Invoke-Expression to run a command that the user enters, verify that the command is safe to run before running it. In general, …

ci: Fix packer does not stop on powershell errors

---

packer/linux_debian.pkr.hcl

For unknown reasons occasionally the source image doesn't contain google-cloud-sdk, causing apt-get purge to fail, which in turn causes packer to fail. Just accept an error while purging google-cloud-sdk.

linux: Don't fail if google-cloud-sdk isn't installed

---

.cirrus.yml
scripts/windows_install_mingw64.ps1

MinGW was installing both `make-4.4-1` and `mingw-w64-ucrt-x86_64-make-4.4-2` packages before, but it started not to install `mingw-w64-ucrt-x86_64-make-4.4-2` (I am not sure why). I added that package. 
Also, Windows VM installation's `skip: !changesInclude` part didn't have `scripts/windows*` but when this is added; linux images' installation will be triggered too. I refactored that part.
CI Run after fix applied: https://cirrus-ci.com/task/6566742164504576

Fix IPC:Run installation on MinGW

---

scripts/bsd/openbsd-prep-postgres.sh

Adding 'noatime' and 'softdep' to the mount points for performance improvements. OpenBSD tasks takes around ~15 minutes now, it was ~22 minutes before. 
Example task: https://cirrus-ci.com/task/5556623333654528
Mount options: https://man.openbsd.org/mount.8
**noatime:**
- Do not update atime on files in the system unless the mtime or ctime is being changed as well. This option is useful for laptops and news servers where one does not want the extra disk activity associated with updating the atime.
**softdep:**
- (FFS only) Mount the file system using soft dependencies. Instead of metadata being written immediately, it is written in an ordered fashion to keep the on-disk state of the file system consistent. This results in significant speedups for file create/delete operations. This option …

openbsd: Add noatime and softdep to the mount points

---

.cirrus.yml
packer/freebsd.pkr.hcl
packer/linux_debian.pkr.hcl
packer/netbsd.pkrvars.hcl
packer/netbsd_openbsd.pkr.hcl
packer/openbsd.pkrvars.hcl
packer/windows.pkr.hcl

Not assign the family inside packer, but do it afterwards, after the permission has been set up.
Fixes #50.

ci: Add family to the images after packer succeeds

---

packer/windows.pkr.hcl

MSYS2 might spawn processes that will stay around in the background forever. They need to be killed. 
See: https://www.msys2.org/docs/ci/

mingw: Fix msys hangs

---

scripts/windows_install_openssl.ps1

It seems the link is updated, v1.1.1t's link is broken.

windows: update openssl to v1.1.1u

---

docker/linux_debian_packer

Container installation was failing with google-cloud-sdk's repository is not signed error. ~Tried to use recommended installation method from 'https://cloud.google.com/sdk/docs/install' but it says '--keyring' is deprecated. So, 'gpg' is used for signing google-cloud-sdk's repository.~ 
apt-key manpage states that '.asc' extension needs to be used when ASCII armored keys are used. So, extension of the keyring file is changed to '.asc'

docker: Fix google-cloud-sdk installation

---

.cirrus.yml
gcp_delete_leftover_running.py
gcp_delete_old_images.py

There could be some leftover VMs. Clear these VMs because of their costs and to get back the space their disks occupy.
It is set to get VMs older than 23 hours instead of 1 day because cron job runs daily, so there could be race conditions.

ci: Delete VMs older than 23 hours

---

packer/freebsd.pkr.hcl
scripts/bsd/netbsd-prep-postgres.sh
scripts/bsd/openbsd-prep-postgres.sh
scripts/linux_debian_install_deps.sh
scripts/windows_install_mingw64.ps1

Install pip while creating the images.
This will help to complete https://github.com/anarazel/postgres/issues/81.

ci: Install pip

---

packer/freebsd.pkr.hcl
packer/linux_debian.pkr.hcl
packer/netbsd_openbsd.pkr.hcl

Use c2-standard-4 for the all instances since it is cheaper compared to other instance types.

ci: Use c2-standard-4 instances

---

.cirrus.yml

cleanup-old task was depending on other to avoid deleting all image versiong when image creation has failed for a few days. However, it is not needed because gcp_delete_olg_images.py script already filters newest image in the families when deleting images.

ci: Remove dependency on cleanup-old task

---

.cirrus.yml

Windows container generation will be dropped. Set trigger_type manual for now.

ci: windows: disable windows container generation

---

.cirrus.yml

The actual version was bumped in https://github.com/anarazel/pg-vm-images/pull/60, but the version in .cirrus.yml wasn't bumped, meaning the image family still ended with 7-2.

Bump OpenBSD version in Cirrus task too.

---

.cirrus.yml
docker/linux_debian_packer
gcp_delete_old_images.py

When it tries to delete old docker images, it fails with `Precondition check failed` error. This could be related to permission issues. I am creating this PR as a draft because I need change `createTime filter` to 2 weeks and test if it is a permission issue.

ci: Delete old docker images

---

.cirrus.yml
packer/windows.pkr.hcl

There's a lot of redundant data in the two images, and the image storage
costs are starting to be noticable; so merge these images.
I tested and confirmed it is working. This PR needs to merged together with https://github.com/anarazel/postgres/pull/84.
Closes #65

ci: windows: Merge windows images

---

packer/freebsd.pkr.hcl

There seems to be a problem in 1.18 that breaks PostgreSQL's interactive tests.  Until a fixed package rolls out, downgrade to 1.17 if 1.18 is detected.
https://github.com/cpan-authors/IO-Tty/issues/38
https://www.postgresql.org/message-id/flat/757523.1705091568%40sss.pgh.pa.us

Downgrade FreeBSD p5-IO-Tty 1.18->1.17.

---

packer/freebsd.pkr.hcl

FreeBSD got a new version 1.20 which is still not fixed.  Unfortunately my earlier workaround would only do a downgrade 1.18->1.17, thinking that the next release would surely be fixed, so we'd get a smooth transition when the new package showed up.  But it's still broken, so we must now downgrade 1.20->1.17.
Fortunately the real fix is coming, hopefully in the next package, based on:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276535

Update work-around for FreeBSD p5-IO-Tty package.

---

scripts/bsd/netbsd-prep-gce.sh

pkgin's repository is not updated when it is installed, it was using NetBSD 9.0's repository, so update pkgin's repository after it is installed.
This should fix recent NetBSD failures.

Fix NetBSD build failures

---

.cirrus.yml
Makefile
docker/linux_debian_ci
packer/linux_debian.pkr.hcl

I tested the new debian 12 images, CI run: https://cirrus-ci.com/build/4851369497067520
```
grub-install --target=x86_64-efi --efi-directory=/boot/efi
```
fixes the errors while creating debian 11 images too. I could make it separate commit or create another PR for it.
I didn't update 'linux_debian_packer' to bookworm because 'Clean up old images' started to fail. CI run: https://cirrus-ci.com/task/4831203417653248.
I spent some time but I couldn't fix it yet. The podman command fails with:
- 'overlay is not supported over overlayfs'. I am able to fix it with installing 'fuse-overlayfs'. Then it failed with:
- '/var/lib/containers/storage/overlay flags: 0x1000: permission denied'. I couldn't fix it yet. It is said that it could be related with apparmor on web.

linux: Upgrade Debian from 11 (bullseye) to 12 (bookworm)

---

packer/freebsd.pkr.hcl

freebsd 13.2 is not available on GCP anymore. Also, python2* and python38 packages are removed as well.

freebsd: Update to 13.3

---

packer/windows.pkr.hcl

Reverts anarazel/pg-vm-images#99
As it turns out the choco ccache is slower, due to some wrappers choco uses. It's faster to just the mingw one.

Revert "windows: Install ccache on VM image"

---

.cirrus.yml
Makefile
README.md
packer/netbsd_openbsd.pkr.hcl

This originally was https://github.com/anarazel/pg-vm-images/pull/85 but github automatically closed it when I pushed a too old version for a rebase - now I can't push again.

Remove version suffix from {Net,Open}BSD image family name.

---

files/bsd/rc.local.sh
packer/netbsd.pkrvars.hcl
packer/netbsd_openbsd.pkr.hcl
packer/openbsd.pkrvars.hcl
scripts/bsd/clear_users_and_ssh_keys.sh
scripts/bsd/netbsd-prep-gce.sh
scripts/bsd/netbsd-prep-postgres.sh
scripts/bsd/openbsd-prep-gce.sh
scripts/bsd/openbsd-prep-postgres.sh

To see all changes from one place, I did not create separate PRs. I can create seperate PRs if you prefer that. If you plan to merge this PR, please merge #89 before.
* Improvements:
* bsd: Add BASE_IMAGE_IDENTITY variable
* bsd: Add 'set -e' to the BSD shell scripts
* Bug fix:
* openbsd: Fix python3 installation on OpenBSD
* Upgrade:
* openbsd: Upgrade OpenBSD to 7.5
* netbsd: Upgrade NetBSD to 10.0
* CI Run after all the changes applied: https://cirrus-ci.com/build/6444335992930304

{Net,Open}BSD upgrade and improvements

---

scripts/bsd/netbsd-prep-postgres.sh

Python 3.9 is not available anymore on NetBSD, so bump it to 3.12.

netbsd: Bump Python version to 3.12

---

scripts/bsd/netbsd-prep-gce.sh
scripts/bsd/openbsd-prep-gce.sh

If there is no ssh-key whose username is root, then it was impossible to access root permissions. With this change, all users can access root permissions by using sudo command.

bsd: Install sudo in OpenBSD and NetBSD

---

files/bsd/rc.local.sh
scripts/bsd/netbsd-prep-postgres.sh

This patch installs mit-krb5 package for gss to work on NetBSD.

netbsd: Install mit-krb5 package for gss to work

---

.cirrus.yml
Makefile
README.md
packer/freebsd.pkr.hcl

freeBSD 13.3 has reached its EOL, update needs to be done. There is already a new major freeBSD version (14). So, instead of updating it to 13.*, upgrade it to 14.2.
This also fixes the TCL problem, so this part of the code is removed.
---
~packer needs to be updated, otherwise freeBSD task hangs at SSH part. Please merge #110 first.~
Postgres CI task that uses freeBSD 14.2: https://cirrus-ci.com/task/6206335622053888
(Also I am sorry that I used your freebsd-14 branch by mistake.)

freebsd: Upgrade to 14.2

---

packer/freebsd.pkr.hcl

FreeBSD image is upgraded to FreeBSD 14. This work-around is not necessary anymore.

freebsd: Remove FreeBSD p5-IO-Tty work-around

---

.cirrus.yml
Makefile
README.md
packer/freebsd.pkr.hcl

Previously, all version updated required changes in the Postgres code base. With this change, this won't be necessary anymore.

freebsd: Remove version suffix from image names'

---

packer/openbsd.pkrvars.hcl
scripts/bsd/openbsd-prep-postgres.sh

7.5 version is removed from OpenBSD CDN. Upgrade OpenBSD to the latest version (7.7).
python3 binary is installed as default now, so symbolic link fix is removed.
CI Task: https://cirrus-ci.com/task/6182340436688896

openbsd: Upgrade OpenBSD to 7.7
